version: '3'

services:
  environment:
    image: spectrumchallenge2/22_spectrum_challenge:phase1_test_env
    network_mode: "host"
  agent: 
    image: agent:latest
    network_mode: "host"
    depends_on:
      - environment
